development:
  sessions:
    default:
      database: lostag
      hosts:
        - localhost:27017
      options:
        consistency: strong
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
